name: hanabi test

on:
  push:
    branches:
      - hanabi
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: hanabi